apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/Nikolai1991/canary-app.git
    targetRevision: HEAD
    path: kubernetes-manifests/bubble-app/

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default  

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial