apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bubble-app
  labels:
    app: bubble-app
spec:
  strategy:
    # which strategy to use (blueGreen, canary..)
    canary:
    # this part represents all the steps during an update.
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 2 # delay starting analysis run until setWeight: 40%
        args:
        - name: service-name
          value: bubble-app-canary.default.svc.cluster.local
      steps:
    # we send at the beginning of the new release 20% of the traffic to the canary release.
    # To do that, Argo CD will update the weight of Istio's VirtualService.
      - setWeight: 20
    # Then we wait 1min to generate some traffic on the canary release.
      - pause:
          duration: "1m"
    # After 1 min, we send 50% of the traffic to the canary release.
      - setWeight: 50
    # Then we wait again 2min
      - pause:
          duration: "2m"
    # At the end if no more step is present, 
    # Argo will send 100% of the traffic to the canary release.
      canaryService: bubble-app-canary # represents our canary clusterIP service.
      stableService: bubble-app-stable # represents our main clusterIP service.
      trafficRouting:
        istio:
           virtualService: 
            name: bubble-app-vs
            routes:
            - bubble-app-rt # At least one route is required
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bubble-app
      version: blue
  template:
    metadata:
      labels:
        app: bubble-app
        version: blue
    spec:
      containers:
      - name: bubble-app
        image: argoproj/rollouts-demo:blue # blue (stable) / orange (new canary version) / bad-green  (broken image)
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "140m"
