apiVersion: v1
kind: Service
metadata:
  name: bubble-app-canary
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bubble-app
  type: ClusterIP
  
---
apiVersion: v1
kind: Service
metadata:
  name: bubble-app-stable
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bubble-app
  type: ClusterIP