apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.AppName }}
  labels:
    app: {{ .Values.AppName }}
spec:
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: {{ .Values.CanaryServiceName }}.default.svc.cluster.local
      steps:
      - setWeight: {{ .Values.FirstWeight }}
      - pause:
          duration: {{ .Values.FirstDuration }}
      - setWeight: {{ .Values.SecondWeight }}
      - pause:
          duration: {{ .Values.SecondDuration }}
      canaryService: {{ .Values.CanaryServiceName }} 
      stableService: {{ .Values.StableServiceName }}
      trafficRouting:
        istio:
           virtualService: 
            name: {{ .Values.VirtualService }}
            routes:
            - {{ .Values.RouteName }}
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
      - name: {{ .Values.AppName }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
