apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.CanaryServiceName }}
  name: {{ .Values.CanaryServiceName }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.AppName }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.StableServiceName }}
  name: {{ .Values.StableServiceName }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.AppName }}
  type: ClusterIP