apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.CanaryServiceName }}
  name: {{ .Values.CanaryServiceName }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: {{ .Values.AppName }}
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.CanaryServiceName }}
  labels:
    account: {{ .Values.CanaryServiceName }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.StableServiceName }}
  name: {{ .Values.StableServiceName }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: {{ .Values.AppName }}
  type: ClusterIP
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ .Values.StableServiceName }}
#   labels:
#     account: {{ .Values.AppName }}