apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.VirtualService }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.AppName }}
spec:
  hosts:
  - {{ .Values.DomainName }}
  gateways:
  - {{ .Values.GatewayName }}
  http:
    - name: {{ .Values.RouteName }}
      route:
        - destination:
            host: {{ .Values.CanaryServiceName }}
            # subset: v1
          weight: 100
        - destination:
            host: {{ .Values.StableServiceName }}
            # subset: v1
          weight: 0
